export type EstadoComercialProspecto =
	| 'PROSPECTO_CARGADO'
	| 'EJECUTIVO_COMERCIAL_ASIGNADO'
	| 'CONTACTO_INICIAL'
	| 'ESTUDIO_SOLICITADO'
	| 'ESTUDIO_EN_DESARROLLO'
	| 'COTIZACION_SOLICITADA_COMPANY'
	| 'ESTUDIO_DISPONIBLE'
	| 'ESTUDIO_ENVIADO_CLIENTE'
	| 'RECOTIZACION_SOLICITADA'
	| 'CERRADO_GANADO'
	| 'CERRADO_PERDIDO'

export type FiltroEstadoComercialValor = EstadoComercialProspecto | 'todos'
