export type EstadoComercialProspecto =
	| 'PROSPECTO_CARGADO'
	| 'EJECUTIVO_COMERCIAL_ASIGNADO'
	| 'CONTACTO_INICIAL'
	| 'ESTUDIO_SOLICITADO'
	| 'ESTUDIO_EN_DESARROLLO'
	| 'COTIZACION_SOLICITADA_COMPANY'
	| 'ESTUDIO_DISPONIBLE'
	| 'ESTUDIO_ENVIADO_CLIENTE'
	| 'RECOTIZACION_SOLICITADA'
	| 'CERRADO_GANADO'
	| 'CERRADO_PERDIDO'

export const ESTADOS_PROSPECTO: EstadoComercialProspecto[] = [
	'PROSPECTO_CARGADO',
	'EJECUTIVO_COMERCIAL_ASIGNADO',
	'CONTACTO_INICIAL',
	'ESTUDIO_SOLICITADO',
	'ESTUDIO_EN_DESARROLLO',
	'COTIZACION_SOLICITADA_COMPANY',
	'ESTUDIO_DISPONIBLE',
	'ESTUDIO_ENVIADO_CLIENTE',
	'RECOTIZACION_SOLICITADA',
	'CERRADO_GANADO',
	'CERRADO_PERDIDO',
]

export const ESTADO_PROSPECTO_LABELS: Record<EstadoComercialProspecto, string> =
	{
		PROSPECTO_CARGADO: 'Nuevo',
		EJECUTIVO_COMERCIAL_ASIGNADO: 'Ejecutivo asignado',
		CONTACTO_INICIAL: 'Contactado',
		ESTUDIO_SOLICITADO: 'Estudio solicitado',
		ESTUDIO_EN_DESARROLLO: 'Estudio en desarrollo',
		COTIZACION_SOLICITADA_COMPANY: 'Cotización solicitada',
		ESTUDIO_DISPONIBLE: 'Estudio disponible',
		ESTUDIO_ENVIADO_CLIENTE: 'Enviado al cliente',
		RECOTIZACION_SOLICITADA: 'Recotización',
		CERRADO_GANADO: 'Ganado',
		CERRADO_PERDIDO: 'Perdido',
	}
