export type EstadoComercialProspecto =
	| 'COTIZACION_DISPONIBLE'
	| 'CONTACTADO'
	| 'ESTUDIO_DISPONIBLE'
	| 'RECOTIZACION_SOLICITADA'
	| 'CLIENTE_CARGADO_MASIVO'
	| 'GANADO'
	| 'PERDIDO'
	| 'COTIZACION_SOLICITADA_COMPANY'
	| 'ESTUDIO_ENVIADO_CLIENTE'
	| 'EJECUTIVO_COMERCIAL_ASIGNADO'
	| 'OPORTUNIDAD_CREADA'
	| 'PROPUESTA_ACEPTADA'
	| 'POLIZA_REGISTRADA'
	| 'PLAN_PAGO_CREADO'

export const ESTADOS_PROSPECTO: EstadoComercialProspecto[] = [
	'COTIZACION_DISPONIBLE',
	'CONTACTADO',
	'ESTUDIO_DISPONIBLE',
	'RECOTIZACION_SOLICITADA',
	'CLIENTE_CARGADO_MASIVO',
	'GANADO',
	'PERDIDO',
	'COTIZACION_SOLICITADA_COMPANY',
	'ESTUDIO_ENVIADO_CLIENTE',
	'EJECUTIVO_COMERCIAL_ASIGNADO',
	'OPORTUNIDAD_CREADA',
	'PROPUESTA_ACEPTADA',
	'POLIZA_REGISTRADA',
	'PLAN_PAGO_CREADO',
]

export const ESTADO_PROSPECTO_LABELS: Record<EstadoComercialProspecto, string> =
	{
		COTIZACION_DISPONIBLE: 'Cotización disponible',
		CONTACTADO: 'Contactado',
		ESTUDIO_DISPONIBLE: 'Estudio disponible',
		RECOTIZACION_SOLICITADA: 'Recotizacion solicitada',
		CLIENTE_CARGADO_MASIVO: 'Cliente cargado desde archivo excel',
		GANADO: 'Ganado',
		PERDIDO: 'Perdido',
		COTIZACION_SOLICITADA_COMPANY: 'Cotización solicitada',
		ESTUDIO_ENVIADO_CLIENTE: 'Estudio enviado al cliente',
		EJECUTIVO_COMERCIAL_ASIGNADO: 'Ejecutivo comercial asignado',
		OPORTUNIDAD_CREADA: 'Oportunidad creada',
		PROPUESTA_ACEPTADA: 'Propuesta aceptada',
		POLIZA_REGISTRADA: 'Póliza registrada',
		PLAN_PAGO_CREADO: 'Plan de pago creado',
	}
