export type EstadoComercialProspecto =
	| 'OPORTUNIDAD_CREADA'
	| 'EJECUTIVO_COMERCIAL_ASIGNADO'
	| 'CONTACTADO'
	| 'ESTUDIO_EN_DESARROLLO'
	| 'COTIZACION_SOLICITADA_COMPANY'
	| 'ESTUDIO_DISPONIBLE'
	| 'ESTUDIO_ENVIADO_CLIENTE'
	| 'RECOTIZACION_SOLICITADA'
	| 'PROPUESTA_ACEPTADA'
	| 'GANADO'
	| 'PERDIDO'

export const ESTADOS_PROSPECTO: EstadoComercialProspecto[] = [
	'OPORTUNIDAD_CREADA',
	'EJECUTIVO_COMERCIAL_ASIGNADO',
	'CONTACTADO',
	'ESTUDIO_EN_DESARROLLO',
	'COTIZACION_SOLICITADA_COMPANY',
	'ESTUDIO_DISPONIBLE',
	'ESTUDIO_ENVIADO_CLIENTE',
	'RECOTIZACION_SOLICITADA',
	'PROPUESTA_ACEPTADA',
	'GANADO',
	'PERDIDO',
]

export const ESTADO_PROSPECTO_LABELS: Record<EstadoComercialProspecto, string> =
	{
		OPORTUNIDAD_CREADA: 'Oportunidad creada',
		EJECUTIVO_COMERCIAL_ASIGNADO: 'Ejecutivo asignado',
		CONTACTADO: 'Contactado',
		ESTUDIO_EN_DESARROLLO: 'Estudio en desarrollo',
		COTIZACION_SOLICITADA_COMPANY: 'Cotización solicitada',
		ESTUDIO_DISPONIBLE: 'Estudio disponible',
		ESTUDIO_ENVIADO_CLIENTE: 'Enviado al cliente',
		RECOTIZACION_SOLICITADA: 'Recotización',
		PROPUESTA_ACEPTADA: 'Propuesta aceptada',
		GANADO: 'Ganado',
		PERDIDO: 'Perdido',
	}
